sudo: false
language: php
php:
  - 7.0
  - 7.1

before_install:
  - composer self-update

install:
  - composer require "squizlabs/php_codesniffer=*"

script:
  - vendor/bin/phpcs --standard=PSR2 -v app/
  - vendor/bin/phpcs --standard=PSR2 -v bootstrap/

notifications:
  email:
    recipients:
      - eu@henriquearthur.com.br
    on_success: change
    on_failure: always
